global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

# rules_files:

scrape_configs:
  - job_name: "payment-server"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["payment-server:8080"]
        labels:
          application: "payment-server"

  - job_name: "payment-client"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["payment-client:5000"]
        labels:
          application: "payment-client"

  - job_name: "otel-collector"
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          application: "node-exporter"
