{
 "title": "Client - Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hitung rate sum dengan label handler",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (handler, method, status) (\n  label_replace(\n    rate(user_handler_request_duration_sum[1m]), \n    \"handler\", \"Userhandler\", \"\", \"\"\n  )\n) or\nsum by (handler, method, status) (\n  label_replace(\n    rate(auth_handler_request_duration_sum[1m]), \n    \"handler\", \"Authhandler\", \"\", \"\"\n  )\n) or\nsum by (handler, method, status) (\n  label_replace(\n    rate(saldo_handler_request_duration_sum[1m]), \n    \"handler\", \"Saldohandler\", \"\", \"\"\n  )\n) or\nsum by (handler, method, status) (\n  label_replace(\n    rate(category_handler_request_duration_sum[1m]), \n    \"handler\", \"Categoryhandler\", \"\", \"\"\n  )\n) or\nsum by (handler, method, status) (\n  label_replace(\n    rate(transfer_handler_request_duration_sum[1m]), \n    \"handler\", \"Transferhandler\", \"\", \"\"\n  )\n) or\nsum by (handler, method, status) (\n  label_replace(\n    rate(withdraw_handler_request_duration_sum[1m]), \n    \"handler\", \"Withdrawhandler\", \"\", \"\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hitung rate count dengan label handler",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (handler, method, status) (\n  label_replace(\n    rate(user_handler_request_duration_count[1m]), \n    \"handler\", \"Userhandler\", \"\", \"\"\n  )\n) or\nsum by (handler, method, status) (\n  label_replace(\n    rate(auth_handler_request_duration_count[1m]), \n    \"handler\", \"Authhandler\", \"\", \"\"\n  )\n) or\nsum by (handler, method, status) (\n  label_replace(\n    rate(saldo_handler_request_duration_count[1m]), \n    \"handler\", \"Saldohandler\", \"\", \"\"\n  )\n) or\nsum by (handler, method, status) (\n  label_replace(\n    rate(category_handler_request_duration_count[1m]), \n    \"handler\", \"Categoryhandler\", \"\", \"\"\n  )\n) or\nsum by (handler, method, status) (\n  label_replace(\n    rate(transfer_handler_request_duration_count[1m]), \n    \"handler\", \"Transferhandler\", \"\", \"\"\n  )\n) or\nsum by (handler, method, status) (\n  label_replace(\n    rate(withdraw_handler_request_duration_count[1m]), \n    \"handler\", \"Withdrawhandler\", \"\", \"\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rata-rata latency semua handler",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": " (\n  sum by (handler, method, status) (\n    label_replace(rate(user_handler_request_duration_sum[1m]), \"handler\", \"Userhandler\", \"\", \"\")\n  ) or\n  sum by (handler, method, status) (\n    label_replace(rate(auth_handler_request_duration_sum[1m]), \"handler\", \"Authhandler\", \"\", \"\")\n  ) or\n  sum by (handler, method, status) (\n    label_replace(rate(saldo_handler_request_duration_sum[1m]), \"handler\", \"Saldohandler\", \"\", \"\")\n  ) or\n  sum by (handler, method, status) (\n    label_replace(rate(category_handler_request_duration_sum[1m]), \"handler\", \"Categoryhandler\", \"\", \"\")\n  ) or\n  sum by (handler, method, status) (\n    label_replace(rate(transfer_handler_request_duration_sum[1m]), \"handler\", \"Transferhandler\", \"\", \"\")\n  ) or\n  sum by (handler, method, status) (\n    label_replace(rate(withdraw_handler_request_duration_sum[1m]), \"handler\", \"Withdrawhandler\", \"\", \"\")\n  )\n)\n/\n(\n  sum by (handler, method, status) (\n    label_replace(rate(user_handler_request_duration_count[1m]), \"handler\", \"Userhandler\", \"\", \"\")\n  ) or\n  sum by (handler, method, status) (\n    label_replace(rate(auth_handler_request_duration_count[1m]), \"handler\", \"Authhandler\", \"\", \"\")\n  ) or\n  sum by (handler, method, status) (\n    label_replace(rate(saldo_handler_request_duration_count[1m]), \"handler\", \"Saldohandler\", \"\", \"\")\n  ) or\n  sum by (handler, method, status) (\n    label_replace(rate(category_handler_request_duration_count[1m]), \"handler\", \"Categoryhandler\", \"\", \"\")\n  ) or\n  sum by (handler, method, status) (\n    label_replace(rate(transfer_handler_request_duration_count[1m]), \"handler\", \"Transferhandler\", \"\", \"\")\n  ) or\n  sum by (handler, method, status) (\n    label_replace(rate(withdraw_handler_request_duration_count[1m]), \"handler\", \"Withdrawhandler\", \"\", \"\")\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}