{
 "title": "Server - Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hitung rate sum dengan label service",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service, method, status) (\n  label_replace(\n    rate(user_service_request_duration_sum[1m]), \n    \"service\", \"UserService\", \"\", \"\"\n  )\n) or\nsum by (service, method, status) (\n  label_replace(\n    rate(auth_service_request_duration_sum[1m]), \n    \"service\", \"AuthService\", \"\", \"\"\n  )\n) or\nsum by (service, method, status) (\n  label_replace(\n    rate(saldo_service_request_duration_sum[1m]), \n    \"service\", \"SaldoService\", \"\", \"\"\n  )\n) or\nsum by (service, method, status) (\n  label_replace(\n    rate(category_service_request_duration_sum[1m]), \n    \"service\", \"CategoryService\", \"\", \"\"\n  )\n) or\nsum by (service, method, status) (\n  label_replace(\n    rate(transfer_service_request_duration_sum[1m]), \n    \"service\", \"TransferService\", \"\", \"\"\n  )\n) or\nsum by (service, method, status) (\n  label_replace(\n    rate(withdraw_service_request_duration_sum[1m]), \n    \"service\", \"WithdrawService\", \"\", \"\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hitung rate count dengan label service",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service, method, status) (\n  label_replace(\n    rate(user_service_request_duration_count[1m]), \n    \"service\", \"UserService\", \"\", \"\"\n  )\n) or\nsum by (service, method, status) (\n  label_replace(\n    rate(auth_service_request_duration_count[1m]), \n    \"service\", \"AuthService\", \"\", \"\"\n  )\n) or\nsum by (service, method, status) (\n  label_replace(\n    rate(saldo_service_request_duration_count[1m]), \n    \"service\", \"SaldoService\", \"\", \"\"\n  )\n) or\nsum by (service, method, status) (\n  label_replace(\n    rate(category_service_request_duration_count[1m]), \n    \"service\", \"CategoryService\", \"\", \"\"\n  )\n) or\nsum by (service, method, status) (\n  label_replace(\n    rate(transfer_service_request_duration_count[1m]), \n    \"service\", \"TransferService\", \"\", \"\"\n  )\n) or\nsum by (service, method, status) (\n  label_replace(\n    rate(withdraw_service_request_duration_count[1m]), \n    \"service\", \"WithdrawService\", \"\", \"\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rata-rata latency semua service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": " (\n  sum by (service, method, status) (\n    label_replace(rate(user_service_request_duration_sum[1m]), \"service\", \"UserService\", \"\", \"\")\n  ) or\n  sum by (service, method, status) (\n    label_replace(rate(auth_service_request_duration_sum[1m]), \"service\", \"AuthService\", \"\", \"\")\n  ) or\n  sum by (service, method, status) (\n    label_replace(rate(saldo_service_request_duration_sum[1m]), \"service\", \"SaldoService\", \"\", \"\")\n  ) or\n  sum by (service, method, status) (\n    label_replace(rate(category_service_request_duration_sum[1m]), \"service\", \"CategoryService\", \"\", \"\")\n  ) or\n  sum by (service, method, status) (\n    label_replace(rate(transfer_service_request_duration_sum[1m]), \"service\", \"TransferService\", \"\", \"\")\n  ) or\n  sum by (service, method, status) (\n    label_replace(rate(withdraw_service_request_duration_sum[1m]), \"service\", \"WithdrawService\", \"\", \"\")\n  )\n)\n/\n(\n  sum by (service, method, status) (\n    label_replace(rate(user_service_request_duration_count[1m]), \"service\", \"UserService\", \"\", \"\")\n  ) or\n  sum by (service, method, status) (\n    label_replace(rate(auth_service_request_duration_count[1m]), \"service\", \"AuthService\", \"\", \"\")\n  ) or\n  sum by (service, method, status) (\n    label_replace(rate(saldo_service_request_duration_count[1m]), \"service\", \"SaldoService\", \"\", \"\")\n  ) or\n  sum by (service, method, status) (\n    label_replace(rate(category_service_request_duration_count[1m]), \"service\", \"CategoryService\", \"\", \"\")\n  ) or\n  sum by (service, method, status) (\n    label_replace(rate(transfer_service_request_duration_count[1m]), \"service\", \"TransferService\", \"\", \"\")\n  ) or\n  sum by (service, method, status) (\n    label_replace(rate(withdraw_service_request_duration_count[1m]), \"service\", \"WithdrawService\", \"\", \"\")\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}